# Generated by Django 6.0.7 on 2026-07-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
