# Generated by Django 6.0.7 on 2026-07-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cus_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='cus_ph',
            new_name='phone_number',
        ),
    ]
