# Generated by Django 6.0.7 on 2026-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_rename_cus_name_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
