# Generated by Django 6.0.7 on 2026-07-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
