# Generated by Django 6.0.7 on 2026-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
